// 风险名单库管理
export const BLACK_LIST = 'BLACK_LIST'

export const GET_BLACK_LIST = 'GET_BLACK_LIST'
export const GET_BLACK_LIST_TYPE_LIST = 'GET_BLACK_LIST_TYPE_LIST'
export const BLACK_SAVE = 'BLACK_SAVE'
export const BLACK_DELETE = 'BLACK_DELETE'
export const BLACK_UPLOAD = 'BLACK_UPLOAD'

export const GET_BLACK_LIST_SUCCESS = 'GET_BLACK_LIST_SUCCESS'
export const GET_BLACK_LIST_TYPE_LIST_SUCCESS = 'GET_BLACK_LIST_TYPE_LIST_SUCCESS'
export const BLACK_SAVE_SUCCESS = 'BLACK_SAVE_SUCCESS'
export const BLACK_DELETE_SUCCESS = 'BLACK_DELETE_SUCCESS'
export const BLACK_UPLOAD_SUCCESS = 'BLACK_UPLOAD_SUCCESS'

export const GET_BLACK_LIST_ERROR = 'GET_BLACK_LIST_ERROR'
export const GET_BLACK_LIST_TYPE_LIST_ERROR = 'GET_BLACK_LIST_TYPE_LIST_ERROR'
export const BLACK_SAVE_ERROR = 'BLACK_SAVE_ERROR'
export const BLACK_DELETE_ERROR = 'BLACK_DELETE_ERROR'
export const BLACK_UPLOAD_ERROR = 'BLACK_UPLOAD_ERROR'
