// 决策树管理管理
// 指标管理
export const DECISION_INDICATORS = 'DECISION_INDICATORS'
// 策略管理
export const DECISION_STRATEGY = 'DECISION_STRATEGY'
export const DECISION_STRATEGY_NEW = 'DECISION_STRATEGY_NEW'
export const DECISION_STRATEGY_NEW_NODEINFO = 'DECISION_STRATEGY_NEW_NODEINFO'
export const DECISION_STRATEGY_NEW_BASICINFO = 'DECISION_STRATEGY_NEW_BASICINFO'
export const DECISION_STRATEGY_NEW_CONFIG = 'DECISION_STRATEGY_NEW_CONFIG'
export const GET_DECISION_SELECT = 'GET_DECISION_SELECT'
export const GET_DECISION_SELECT_SUCCESS = 'GET_DECISION_SELECT_SUCCESS'
export const GET_DECISION_SELECT_ERROR = 'GET_DECISION_SELECT_ERROR'
export const FLOW_TYPES = {
  BEGIN: 'BEGIN',
  END: 'END',
  RULE_SET: 'RULE_SET',
  D_TREE: 'DECISION_TREE',
  DECISION_NODE: 'DECISION_NODE',
  SCORE_CARD: 'SCORE_CARD',
  RESOURCE: 'RESOURCE',
  DECISION: 'DECISION'
}
export const DECISION_OPERATOR = {
  greatThan: '大于',
  lessThan: '小于',
  equals: '等于',
  greatEquals: '大于等于',
  lessEquals: '小于等于'
}
export const DECISION_RESULT_COLORS = {
  low: '#F8E71C',
  middle: '#F5A623',
  high: '#D0021B'
}
