// 事件中心
export const EVENT_QUERY = 'EVENT_QUERY'
export const PERSONAL_STATS = 'PERSONAL_STATS'
export const EVENT_OFFLINE = 'EVENT_OFFLINE'

export const GET_PROVINCE_LIST = 'GET_PROVINCE_LIST'
export const GET_CITY_LIST = 'GET_CITY_LIST'
export const OFFLINE_UPLOAD = 'OFFLINE_UPLOAD'
export const OFFLINE_UPLOAD_STATUS = 'OFFLINE_UPLOAD_STATUS'
export const OFFLINE_DOWNLOAD = 'OFFLINE_DOWNLOAD'

export const GET_PROVINCE_LIST_SUCCESS = 'GET_PROVINCE_LIST_SUCCESS'
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS'

export const GET_PROVINCE_LIST_ERROR = 'GET_PROVINCE_LIST_ERROR'
export const GET_CITY_LIST_ERROR = 'GET_CITY_LIST_ERROR'
export const EXPORT_START_ERROR = 'EXPORT_START_ERROR'
export const EXPORT_STATUS_ERROR = 'EXPORT_STATUS_ERROR'
