// 统计报表
export const GET_TODAY_DATA = 'GET_TODAY_DATA'
export const IPPROVINCE = 'IPPROVINCE'
export const IPCITY = 'IPCITY'

export const GET_TODAY_DATA_SUCCESS = 'GET_TODAY_DATA_SUCCESS'

export const GET_TODAY_DATA_ERROR = 'GET_TODAY_DATA_ERROR'
