// 离线验证
export const GET_APP_SELECT = 'GET_APP_SELECT'
export const GET_SCENE_SELECT = 'GET_SCENE_SELECT'
export const GET_OFFLINE_SCENE_SELECT = 'GET_OFFLINE_SCENE_SELECT'

export const GET_APP_SELECT_SUCCESS = 'GET_APP_SELECT_SUCCESS'
export const GET_SCENE_SELECT_SUCCESS = 'GET_SCENE_SELECT_SUCCESS'
export const GET_OFFLINE_SCENE_SELECT_SUCCESS = 'GET_OFFLINE_SCENE_SELECT_SUCCESS'

export const GET_APP_SELECT_ERROR = 'GET_APP_SELECT_ERROR'
export const GET_SCENE_SELECT_ERROR = 'GET_SCENE_SELECT_ERROR'
export const GET_OFFLINE_SCENE_SELECT_ERROR = 'GET_OFFLINE_SCENE_SELECT_ERROR'
